[project]
name = "zero-cache"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "semver>=3.0.4",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
