{{- if and (not .Values.singleNode.enabled) .Values.viewSyncer.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zero-cache.fullname" . }}-view-syncer
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: view-syncer
spec:
  {{- if .Values.viewSyncer.pdb.minAvailable }}
  minAvailable: {{ .Values.viewSyncer.pdb.minAvailable }}
  {{- else if .Values.viewSyncer.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.viewSyncer.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "zero-cache.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: view-syncer
{{- end }}