---
# Database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-cache.fullname" . }}-db
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  upstream-db: {{ required "A valid .Values.common.database.upstreamDb entry is required!" .Values.common.database.upstreamDb | quote }}
  {{- if .Values.common.database.cvrDb }}
  cvr-db: {{ .Values.common.database.cvrDb | quote }}
  {{- end }}
  {{- if .Values.common.database.changeDb }}
  change-db: {{ .Values.common.database.changeDb | quote }}
  {{- end }}
---
# Authentication secret
{{- if or (and .Values.common.auth.secret .Values.common.auth.secret.value) (and .Values.common.auth.jwk .Values.common.auth.jwk.value) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-cache.fullname" . }}-auth
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.common.auth.secret .Values.common.auth.secret.value }}
  auth-secret: {{ .Values.common.auth.secret.value | quote }}
  {{- end }}
  {{- if and .Values.common.auth.jwk .Values.common.auth.jwk.value }}
  auth-jwk: {{ .Values.common.auth.jwk.value | quote }}
  {{- end }}
{{- end }}
---
# Admin password secret
{{- if .Values.common.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-cache.fullname" . }}-admin
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.common.adminPassword | quote }}
{{- end }}
---
# S3 credentials secret
{{- if and .Values.s3.enabled .Values.common.litestream.backupUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-cache.fullname" . }}-s3
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ required "A valid .Values.s3.accessKey is required when .Values.s3.enabled=true!" .Values.s3.accessKey | quote }}
  secret-key: {{ required "A valid .Values.s3.secretKey is required when .Values.s3.enabled=true!" .Values.s3.secretKey | quote }}
{{- end }}