---
# Service for replication-manager
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-cache.fullname" . }}-replication-manager
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: replication-manager
  {{- with .Values.replicationManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.replicationManager.service.type }}
  ports:
    - port: {{ .Values.replicationManager.service.port }}
      targetPort: change-stream
      protocol: TCP
      name: change-stream
  selector:
    {{- include "zero-cache.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replication-manager
---
# Service for view-syncer
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-cache.fullname" . }}-view-syncer
  labels:
    {{- include "zero-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: view-syncer
  annotations:
    # SessionAffinity is recommended for view-syncer to ensure clients consistently connect to the same instance
    service.kubernetes.io/session-affinity: "ClientIP"
    service.kubernetes.io/session-affinity-timeout: "3600"
    {{- with .Values.viewSyncer.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.viewSyncer.service.type }}
  ports:
    - port: {{ .Values.viewSyncer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zero-cache.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: view-syncer