name: Docker Image Version Management

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  packages: write

jobs:
  check-and-update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Manage Docker Image Versions and Helm Chart
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          uv run version_manager.py \
            --docker_image=rocicorp/zero \
            --chart_path=Chart.yaml \
            --values_path=values.yaml \
            --oci_registry=ghcr.io \
            --oci_repo=synapdeck/zero-cache-chart
